### ISSUE TITLE
AccessDenied error when running on readthedocs

### ISSUE THREAD

**Issue by davidanthoff** [tomduck/pandoc-eqnos#10]
I am running pandoc and the pandoc-eqnos filter as part of a documentation build process on readthedocs. This worked with the 0.8 version, but with master I now get an AccessDenied error. The error is thrown [here](https://github.com/tomduck/pandoc-eqnos/blob/master/pandoc_eqnos.py#L72). You can see the whole log output from readthedocs [here](https://readthedocs.org/projects/fundjl/builds/3924204/). The source of my project is [here](https://github.com/davidanthoff/fund.jl), with the specific call to pandoc [here](https://github.com/davidanthoff/fund.jl/blob/master/doc/readthedocsconfig/conf.py#L295).

**Comment by tomduck** [comment]
Rats.  I did a fair bit of refactoring to be able to process attributes, and threw in a few extras.  The psutil code is something I borrowed from my pandoc-fignos filter, where it wasn't causing any trouble.  It seems likely that you don't have sufficient privileges on readthedocs for the parent call.  I will investigate and fix.

**Comment by davidanthoff** [comment]
Great, and thanks a lot! Yes, I'm sure the process on readthedocs is running with some limited privileges.

**Comment by tomduck** [comment]
The question is: "how limited?"  I just pushed some new code to GitHub that will hopefully fix the problem you have encountered.  Please let me know.  There are other options if this fails.

A few details: Pandoc does not supply its version number to filters (see [Issue 2640](https://github.com/jgm/pandoc/issues/2640).  This causes challenges when version-dependent processing needs to be done.  I thought I had a solution in asking the filter's parent process (i.e., pandoc) for version information.  This has worked for others, but not on readthedocs.

The new code falls back to calling the `pandoc` command.  This should work fine for most users, but not for me.  I need the psutil capabilities because I have multiple pandoc executables (i.e., pandoc-1.17.0.2, etc) on my machine for testing purposes.

**Comment by davidanthoff** [comment]
I just tested it, and it all works on readthedocs, great! Thanks so much for the quick resolution.

**Comment by tomduck** [comment]
Fantastic!  Thanks so much for your help with it.  :o)
