### ISSUE TITLE
Bidirectional reference links

### ISSUE THREAD

**Issue by kleinbottle** [tomduck/pandoc-eqnos#25]
I have just noticed that equation references appear as hyperlinks when the equations are referenced in the text.

But the link does not point to the equation nor is there any way to get back to the text from the equation. I am referring to the behaviour that footnotes exhibit at present in pandoc.

Is this function already available but absent for me because I am not invoking pandoc-eqnos properly?

If not, is it an easy feature to implement? If so, might I request an enhancement?

Thanks.

**Comment by tomduck** [comment]
Hi @kleinbottle.  Thanks for your feedback.  I'm not sure what you mean when you say "the link does not point to the equation".  In all of my tests with pdf and html the links do point to the equation.  Can you please explain further?

As for how to get back to the text: Normally this is what the "Go back" button on a browser/reader is for.  Since there can be multiple references pointing to a single figure, it wouldn't be possible (as far as I know) in the document to encode "Go back" behaviour.  It really has to be left up to the browser, I think.

**Comment by tomduck** [comment]
Hi @kleinbottle.  I'm assuming that this is no longer a concern.  Please feel welcome to reopen this Issue if there are problems to discuss.
